# Data Types

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
# more than one dimensions
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
# minimum dimensions
a=np.array([1, 2, 3,4,5], ndmin=3)
print(a)

[[[1 2 3 4 5]]]


In [9]:
# dtype parameter
a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [17]:
# dtype parameter
a = np.array([6,5, -1,-95941, 0], dtype=bool)
print(a)

[ True  True  True  True False]


In [19]:
# dtype parameter
a = np.array([1, 2.0, 3.99999999,-5.9999999999], dtype=int)
print(a)

[ 1  2  3 -5]


In [25]:
# dtype parameter
a = np.array([1, 2.0, 3.99999999,-5.9999999999], dtype=np.intc)
print(a)

[ 1  2  3 -5]


In [24]:
# dtype parameter
a = np.array([1, 2.0, 3.99999999,-5.9999999999], dtype=np.intp)
print(a)
print(a.dtype)

[ 1  2  3 -5]
int64


In [29]:
# dtype parameter
a = np.array([1, 2.0, 3.99999999,-5.9999999999], dtype=np.int8)
print(a)

[ 1  2  3 -5]


In [33]:
# dtype parameter
a = np.array([1, 2.0, 3.99999999,+5.9999999999], dtype=np.uint)
print(a)

[1 2 3 5]


In [36]:
# dtype parameter
a = np.array([1, 2.0, 3.99999999999999,-5.9999999999 , -7.9999], dtype=float)
print(a)

[ 1.      2.      4.     -6.     -7.9999]


In [37]:
# dtype parameter
a = np.array([1, 2.0, 3.99999999999999,-5.9999999999 , -7.9999], dtype=complex)
print(a)

[ 1.    +0.j  2.    +0.j  4.    +0.j -6.    +0.j -7.9999+0.j]


# Data Type Objects (dtype)

In [39]:
# A dtype object is constructed using the following syntax:
# numpy.dtype(object, align, copy)

In [3]:
# using array-scalar type
dt=np.dtype(np.int32)
print(dt)

int32


In [6]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc.
dt = np.dtype('i8')
print(dt)

int64


In [7]:
# using endian notation
dt = np.dtype('>i4')
print(dt)

>i4


In [8]:
# first create structured data type
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [13]:
# now apply it to ndarray object
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [15]:
# file name can be used to access content of age column
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
print(a['age'])

[10 20 30]


In [16]:
student=np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [19]:
student=np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [20]:
# Each built-in data type has a character code that uniquely identifies it.
# 'b': boolean
# 'i': (signed) integer
# 'u': unsigned integer
# 'f': floating-point
# 'c': complex-floating point
# 'm': timedelta
# 'M': datetime
# 'O': (Python) objects
# 'S', 'a': (byte-)string
# 'U': Unicode
# 'V': raw data (void)

# 5. NUMPY − ARRAY ATTRIBUTES

In [22]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [23]:
# this resizes the ndarray
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [29]:
# this is one dimensional array
a = np.arange(24)
a.ndim
# now reshape it
b = a.reshape(2,4,3)
print(b)
# b is having three dimensions

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [30]:
# dtype of array is int8 (1 byte)
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [31]:
# dtype of array is now float32 (4 bytes)
x = np.array([1,2,3,4,5], dtype=np.float32)
print (x.itemsize)

4


In [33]:
x = np.array([1,2,3,4,5])
print ( x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



# 6. NUMPY − ARRAY CREATION ROUTINES

In [34]:
# numpy.empty(shape, dtype=float, order='C')

In [41]:
x = np.empty([3,2], dtype=int)
print(x)  # random values

[[1 2]
 [3 4]
 [5 6]]


In [46]:
shape=(3,4)
np.zeros(shape, dtype=float, order='C')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
# array of five zeros. Default dtype is float
x = np.zeros(5)
print (x)

[0. 0. 0. 0. 0.]


In [49]:
x = np.zeros((5,),dtype=int)
print (x)

[0 0 0 0 0]


In [51]:
x = np.zeros((2,2), dtype=[('x', 'f4'), ('y', 'i4')])
print (x)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


In [52]:
# array of five ones. Default dtype is float
x = np.ones(5)
print (x)

[1. 1. 1. 1. 1.]


In [53]:
x = np.ones([2,2], dtype=int)
print (x)

[[1 1]
 [1 1]]


# 7. NUMPY − ARRAY FROM EXISTING DATA

In [54]:
# convert list to ndarray
x = [1,2,3]
a = np.asarray(x)
print (a)

[1 2 3]


In [55]:
# dtype is float
x = [1,2,3]
a = np.asarray(x, dtype=float)
print (a)

[1. 2. 3.]


In [56]:
# ndarray from tuple
x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [60]:
# ndarray from list of tuples
x = [(1,2,3),(4,5)]
a = np.asarray(x,dtype=object)
print (a)

[(1, 2, 3) (4, 5)]


In [62]:
s = 'Hello World'
a = np.frombuffer(s.encode(), dtype='S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [63]:
s = 'Hello World'
a = np.array(list(s), dtype='U1')  # 'U1' = Unicode string of length 1
print(a)

['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']


In [66]:
list = range(5)
print(list)

range(0, 5)


In [67]:
# obtain iterator object from list

list = range(5)
it = iter(list)
# use iterator to create ndarray
x = np.fromiter(it, dtype=float)
print (x)

[0. 1. 2. 3. 4.]


# 8. NUMPY − ARRAY FROM NUMERICAL RANGES

In [69]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [70]:
# dtype set
x = np.arange(5, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [71]:
# start and stop parameters set
x = np.arange(10,20,2)
print (x)

[10 12 14 16 18]


In [72]:
a = np.linspace(0, 10, num=5)
print(a)

[ 0.   2.5  5.   7.5 10. ]
